name: Build with Theos

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl git ldid fakeroot dpkg-dev make

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo 'export THEOS=$HOME/theos' >> $GITHUB_ENV
          echo 'export PATH=$THEOS/bin:$PATH' >> $GITHUB_ENV

      - name: Build with Theos
        env:
          THEOS: ${{ env.THEOS }}
        run: |
          make package

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: ./packages/*.deb
